# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- prod

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: '$(System.Defaultworkingdirectory)/start/system/pom.xml'
        goals: 'clean package'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    # - task: Docker@2
    #   displayName: Build inventory
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/start/inventory/Dockerfile'
    #    # imageName: jammanaraj/inventory
    #     tags: jammanaraj/myfirstcontainerimage:inventory 
    - task: Docker@2
      displayName: Build system
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/start/system/Dockerfile'
        tags: jammanaraj/myfirstcontainerimage:system
        
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'docker images'
        
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'Docker_ACR'
    #     repository: 'jammanaraj/myfirstcontainerimage'
    #     command: 'buildAndPush'
    #     Dockerfile: '$(Build.SourcesDirectory)/start/inventory/Dockerfile'
    #     tags: inventory

    # - task: Docker@2
    #   displayName: push to docker hub
    #   inputs:
    #     containerRegistry: 'Docker_ACR'
    #     repository: 'jammanaraj/myfirstcontainerimage'
    #     command: 'push'
    #     tags: 'system'